### ISSUE TITLE
Module name quoted with backticks (template literal syntax) is not detected

### ISSUE THREAD

**Issue by zypA13510** [dependents/node-detective-cjs#5]
pahen/madge#173

Looks like the issue is caused by ``require(`module-name`)`` not being recognized. Replacing it with ``require('module-name')`` or ``require("module-name")`` would work.

**Comment by pahen** [comment]
I don't see any reason for fixing this. Only use backticks if the string contains an expression. If you're using eslint it will actually give you an error when using backticks when not needed.

**Comment by zypA13510** [comment]
@pahen I think you mean [quotes - enforce the consistent use of either backticks, double, or single quotes](https://eslint.org/docs/rules/quotes)? Note that backticks are allowed as an option, you can make it mandatory in your code if you wish.

And since ``require(`express`)`` will work, then it is a bug for not detecting that when the job of this package is to find all dependencies. Of course, a true dependency search will need a dynamic analysis as opposed to the static analysis currently used by most ECMAScript parsers, but I think at least we can make static template literals work?

> Only use backticks if the string contains an expression.

Well, then you'd probably argue that among single quote and double quote only one should be allowed, or always/never add semicolon at the end of line? Those religious wars never end ;)

**Comment by mrjoelkemp** [comment]
Thanks for filing the issue, submitting a fix, and for the discussion thus far (appreciate your input @pahen) . 

I do agree that valid syntax not being handled is more of a bug in this case. 

I'm happy to merge the fix when there's a unit test to prove that it works. Great work @zypA13510!

**Comment by pahen** [comment]
Yes I can see that it can be handy to support this too :) Nice job @zypA13510
